name: ë¬¸ì„œ ë°°í¬

on:
  # "main" ë¸Œëœì¹˜ì— í‘¸ì‹œí•  ë•Œë§ˆë‹¤ ì›Œí¬í”Œë¡œìš° ì‘ë™
  push:
    branches: ["main"]

# GitHub Pagesì— ë°°í¬í•˜ê¸° ìœ„í•œ GITHUB_TOKEN ê¶Œí•œ ì„¤ì •
permissions:
  contents: read
  pages: write
  id-token: write

# ë™ì‹œì„± ë°°í¬ í—ˆìš©
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      # GitHub Pagesë¡œ ë°°í¬í•˜ê¸° ìœ„í•œ í•„ìˆ˜ ì„¤ì •
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: macos-latest   # ìµœì‹  macOS ì´ë¯¸ì§€ ì‚¬ìš©

    steps:
      - name: ì²´í¬ì•„ì›ƒ ğŸ›ï¸
        uses: actions/checkout@v3

      - name: Setup Xcode 15.0
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "15.0"

      - name: DocC ë¬¸ì„œ ë¹Œë“œ (ìŠ¤í¬ë¦½íŠ¸ ì‹¤í–‰)
        run: |
          # 1) ìŠ¤í¬ë¦½íŠ¸ ì‹¤í–‰ ê¶Œí•œ ë¶€ì—¬
          chmod +x ./GENERATE_DOCS.sh
          # 2) ìŠ¤í¬ë¦½íŠ¸ ì‹¤í–‰
          ./GENERATE_DOCS.sh

      - name: Pages ì•„í‹°íŒ©íŠ¸ ì—…ë¡œë“œ
        uses: actions/upload-pages-artifact@v1
        with:
          path: "docs"

      - name: GitHub Pagesì— ë°°í¬
        id: deployment
        uses: actions/deploy-pages@v1
